services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    # ports:
    #   - "3000:3000"
    restart: always
    depends_on:
      - db
      - redis
      - filesrv
      - wsgateway
    env_file: ./api/.env
  
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    # ports: 
    #   - "6379:6379" 
    restart: always
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      - redis
  
  wsgateway:
    build:
      context: ./wsgateway
      dockerfile: Dockerfile
    container_name: wsgateway
    # ports:
    #   - "8081:8081"
    restart: always
    depends_on:
      - redis
    env_file: ./wsgateway/.env
    
  db:
    image: postgres:13-alpine
    container_name: db
    restart: always
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema/schema.sql:/docker-entrypoint-initdb.d/10_schema.sql
      - ./db/seed/seed.sql:/docker-entrypoint-initdb.d/20_seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
      - wsgateway
      - filesrv
    restart: always
  
  tbls:
    image: k1low/tbls
    container_name: tbls
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DB_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"
  
  filesrv:
    build:
      context: ./filesrv
      dockerfile: Dockerfile
    container_name: filesrv
    # ports:
    #   - "3131:3131"
    restart: always
    env_file: ./filesrv/.env
    volumes:
      - ./filesrv/uploads:/static/uploads

volumes:
  pgdata:
